Initial progress in new build system:  - add NCEPLIBS_DIR environment variable into configure.upp  - use NCEPLIBS_DIR to point to external build of wrfio libraries  - Remove our build of wrf_io in favor of external build
Compile tested only on Cheyenne, gnu compilers for now

diff --git a/comupp/configure b/comupp/configure
--- a/comupp/configure
+++ b/comupp/configure
@@ -109,6 +109,15 @@ if [ -f "$NETCDF/lib/libnetcdff.a" -o -f "$NETCDF/lib/libnetcdff.so" ] ; then
   USENETCDFF="-lnetcdff"
 fi
 
+# Find location of NCEPLIBS
+if [ -z "$NCEPLIBS_DIR" ] ; then
+  echo "ERROR: You must define the location of the NCEP libraries (NCEPLIBS_DIR)"
+  exit 1
+fi
+
+
+
+
 #
 # if the uname command exists, give it a shot and see if
 # we can narrow the choices; otherwise, spam 'em
@@ -137,9 +146,6 @@ if [ ! -e ./bin ] ; then
    mkdir ./bin
 fi
 
-WRF_DIR=${pwd}/src/lib/wrf_io
-echo "wrfdir " ${WRF_DIR}
-
 BINDIR=${pwd}/bin
 echo "bindir " ${BINDIR}
 
@@ -165,7 +171,7 @@ fi
 
 #
 # so proceed with configuration 
-perl arch/Config.pl  -wrfdir=$WRF_DIR                                \
+perl arch/Config.pl  -nceplibs=$NCEPLIBS_DIR                          \
                      -netcdf=$NETCDF -USENETCDFF=$USENETCDFF          \
                      -os=$os -mach=$mach                              \
                      -bindir=$BINDIR -incmod=$INCMOD -libdir=$LIBDIR  \
